### ISSUE TITLE
java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by agrothe** [arangodb/java-velocypack-module-jdk8#1]
Getting this error occasionally on deserialize, but only when using it from multiple instance of a Vertx Vertical, even when creating a new Parser and VPack instance inside the route handler.

Starting Vertx with:
```
DeploymentOptions options = new DeploymentOptions()
	    		.setConfig(config)
	    		.setInstances(6);
```

If I set Instances to 1, nothing, if > 1 I start getting below error. 

Minimal reproducer is attached here: [test.zip](https://github.com/arangodb/java-velocypack-module-jdk8/files/1150692/test.zip).
Create debug config with:
Main Class: test.Start

I'm using the NPM module `loadtest` like so:

`loadtest -n 20100 -c 6 -k http://localhost:8080/`

`Unexpected exception in route 
com.arangodb.velocypack.exception.VPackParserException: java.lang.NumberFormatException: For input string: ""
	at com.arangodb.velocypack.VPack.deserialize(VPack.java:398)
	at com.bordereast.saasy.cache.ModuleRedisCache.stringToObject(ModuleRedisCache.java:62)
	at com.bordereast.saasy.cache.ModuleRedisCache.getObject(ModuleRedisCache.java:41)
	at com.bordereast.saasy.content.ContentLocator.getModule(ContentLocator.java:135)
	at com.bordereast.saasy.content.ContentLocator.Locate(ContentLocator.java:67)
	at com.bordereast.saasy.routes.ContentHandler.accept(ContentHandler.java:51)
	at com.bordereast.saasy.SaaSyServer.lambda$1(SaaSyServer.java:56)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118)
	at com.bordereast.saasy.routes.AuthHandler.accept(AuthHandler.java:12)
	at com.bordereast.saasy.SaaSyServer.lambda$0(SaaSyServer.java:51)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:202)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:180)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:67)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:406)
	at io.vertx.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:297)
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:441)
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:673)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:580)
	at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(VertxHttpHandler.java:71)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:71)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Long.parseLong(Unknown Source)
	at java.lang.Long.parseLong(Unknown Source)
	at java.text.DigitList.getLong(Unknown Source)
	at java.text.DecimalFormat.parse(Unknown Source)
	at java.text.SimpleDateFormat.subParse(Unknown Source)
	at java.text.SimpleDateFormat.parse(Unknown Source)
	at java.text.DateFormat.parse(Unknown Source)
	at com.arangodb.velocypack.internal.util.DateUtil.parse(DateUtil.java:55)
	at com.arangodb.velocypack.internal.VPackDeserializers$12.deserialize(VPackDeserializers.java:157)
	at com.arangodb.velocypack.internal.VPackDeserializers$12.deserialize(VPackDeserializers.java:148)
	at com.arangodb.velocypack.module.jdk8.internal.VPackJdk8Deserializers.lambda$static$0(VPackJdk8Deserializers.java:47)
	at com.arangodb.velocypack.VPack.getValue(VPack.java:546)
	at com.arangodb.velocypack.VPack.deserializeField(VPack.java:512)
	at com.arangodb.velocypack.VPack.deserializeFields(VPack.java:500)
	at com.arangodb.velocypack.VPack.deserializeObject(VPack.java:451)
	at com.arangodb.velocypack.VPack.getValue(VPack.java:569)
	at com.arangodb.velocypack.VPack.deserialize(VPack.java:396)
	... 47 more`

**Comment by mvollmary** [comment]
@agrothe I fixed a bug in our velocypack parser. If you upgrade to java-driver version `4.2.4` your issue should be solved. At least I couldn't replicate it with your code in that version.
